use csdr develop branch
Updated the git clone command to use the 'develop' branch instead of 'master' due to changes in the repository structure.

This will fix the compiling issue under latest Debian:

```
make
[  1%] Building C object src/CMakeFiles/csdr.dir/libcsdr.c.o
/tmp/csdr_master/src/libcsdr.c:401:9: note: ‘#pragma message: Manual NEON (aarch64) optimizations are ON: we have a faster shift_addfast_cc now.’
  401 | #pragma message "Manual NEON (aarch64) optimizations are ON: we have a faster shift_addfast_cc now."
      |         ^~~~~~~
/tmp/csdr_master/src/libcsdr.c: In function ‘fir_decimate_init’:
/tmp/csdr_master/src/libcsdr.c:564:5: error: implicit declaration of function ‘errhead’; did you mean ‘pread’? [-Wimplicit-function-declaration]
  564 |     errhead(); fprintf(stderr,"taps_length = %d\n", result.taps_length);
      |     ^~~~~~~
      |     pread
/tmp/csdr_master/src/libcsdr.c: At top level:
/tmp/csdr_master/src/libcsdr.c:655:9: note: ‘#pragma message: Manual NEON (aarch64) optimizations are ON: we have a faster fir_decimate_cc now.’
  655 | #pragma message "Manual NEON (aarch64) optimizations are ON: we have a faster fir_decimate_cc now."
      |         ^~~~~~~
make[2]: *** [src/CMakeFiles/csdr.dir/build.make:79: src/CMakeFiles/csdr.dir/libcsdr.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:177: src/CMakeFiles/csdr.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```